### PR TITLE
Improve parsing range checks

### PR DESCRIPTION
**Pull request by Womblue**
This PR fixes the bad `negative argument` error encountered when parsing using `start` values which don't give a large enough range of possible suffixes to cover all nodes in the buffer. When parsing manually, it also prevents the user from selecting more nodes than they can name with the given start value they have chosen.

### CODE REVIEW

**Comment by Womblue** [comment]
Converted to draft while I rewrite this to match new aims for Hunter parsing

**Comment by Womblue** [comment]
New version essentially rolled back a lot of changes from the old version. New behaviour is such that e.g. `parse --prefix node --start 01` will number nodes 01-99 as normal, then continue to 100, 101 etc with no upper limit.

**Comment by VoxSecundus** [comment]
@Womblue Is there any reason this can't be merged now? Would be useful to have this change on my current branch.

**Comment by Womblue** [comment]
It should be fine to merge now yes

**Review by VoxSecundus — APPROVED** [review]

**Pull request merged**
